### ISSUE TITLE
Scripts not loading with Pale Moon 28.6.1

### ISSUE THREAD

**Issue by ghysler** [wol-soft/beerplop-issues#64] opened 2019-08-23 15:52 UTC
I'm unable to open the Beerplop website with Pale Moon 28.6.1 (x64). This issue started around version 1.45 of Beerplop. Loading page stops at "Initializing scripts". I remember it suddenly stopped working and, although I did not change anything to my browser configuration. I switched to Chromium where it works properly, but would prefer to continue to use Pale Moon.

 Could you investigate this? See below error message from the Console, which is probably related.

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.9) Gecko/20100101 Goanna/4.3 Firefox/60.9 PaleMoon/28.6.1

`17:47:59.502 jQuery.Deferred exception: Beerplop is not defined assetPromises["game-js"]</<@https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.0.min.js:51:18
e@https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.0.min.js:2:29451
l/</t<@https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.0.min.js:2:29755
 undefined 1 beerplop-init-1.59.0.min.js:2:30998`

**Comment by wol-soft** [comment] 2019-08-23 19:56
I'll have a look into it at the start of next week.

**Comment by wol-soft** [comment] 2019-08-25 18:09
Hi @ghysler I've changed the loading order a little bit based on the given error message with 1.59.3.

I haven't set up a VM yet to look if it fixes the loading issue. Could you check if the issue is fixed with the new loading order?

Anyhow thanks for the detailled platform description in the issue!

**Comment by ghysler** [comment] 2019-08-25 21:27
Now it hangs at phase "Loading script assets".  Message in console:

`23:25:18.868 SyntaxError: invalid property id 1 plop:2632:9213
	b https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:758
	globalEval https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:2681
	text script https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:81840
	l/s< https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:78358
	l https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:77852
	o/< https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.59.3.min.js:2:81117
`

**Comment by wol-soft** [comment] 2019-08-26 09:38
Hi @ghysler 

I've found the reason for this incompatibility. Pale Moon as well as Edge/IE don't (yet) support some new JavaScript features used in the Bootstrap-Material-Design library Beerplop uses from version 4.1.2 upwards (compare: https://github.com/FezVrasta/bootstrap-material-design/issues/1373).
This matches with your description since when the game is broken in Pale Moon as I updated libraries at that time.

I don't yet know how to solve the issue as i dislike the idea of downgrading the library. I'll have a deeper dive into it later.

**Comment by wol-soft** [comment] 2019-08-26 18:12
Fixed the loading in 1.60.0.

**Closed by wol-soft** 2019-08-26 18:12 UTC
Labels: Platform, bug

**Comment by ghysler** [comment] 2019-08-26 18:33
Thank you for implementing this fix/workaround! Nice work!

I can confirm the game loads now, but I'm seeing a few issues:

* Show current load/level map in the Bar don't have any effect
* Save button in Save States window does not show save notification
* Achievements are not showing

Console shows below error upon opening the game, although I don't know if it is related. 

`20:29:30.880 bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead. 1 beerplop-game-1.60.0.min.js:2637:6208`

**Comment by wol-soft** [comment] 2019-08-26 19:27
Hi @ghysler 

the bootstrap-slider warning can be ignored.

The save message may be a timing thing. It only shows if the save state is persisted to the server. If it just has been persisted a new save is locked for 30 seconds to prevent spamming new saves to the server.

For the other issues you may open new issues 😉
